# Generated by Django 4.2.7 on 2023-12-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_resource_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Developer', 'Userd'), ('staff', 'Staff')], max_length=10),
        ),
    ]
